USE [master]
GO

CREATE DATABASE [VNVCTest]
 CONTAINMENT = NONE
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VNVCTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [VNVCTest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [VNVCTest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [VNVCTest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [VNVCTest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [VNVCTest] SET ARITHABORT OFF 
GO

ALTER DATABASE [VNVCTest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [VNVCTest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [VNVCTest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [VNVCTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [VNVCTest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [VNVCTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [VNVCTest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [VNVCTest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [VNVCTest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [VNVCTest] SET  DISABLE_BROKER 
GO

ALTER DATABASE [VNVCTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [VNVCTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [VNVCTest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [VNVCTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [VNVCTest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [VNVCTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [VNVCTest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [VNVCTest] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [VNVCTest] SET  MULTI_USER 
GO

ALTER DATABASE [VNVCTest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [VNVCTest] SET DB_CHAINING OFF 
GO

ALTER DATABASE [VNVCTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [VNVCTest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [VNVCTest] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [VNVCTest] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [VNVCTest] SET QUERY_STORE = ON
GO

ALTER DATABASE [VNVCTest] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [VNVCTest] SET  READ_WRITE 
GO

USE [VNVCTest]
GO
/****** Object:  Table [dbo].[DatSo]    Script Date: 2023-12-10 2:32:32 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DatSo](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IDNguoiChoi] [int] NULL,
	[Ngay] [datetime] NULL,
	[Gio] [int] NULL,
	[GiaTri] [int] NULL,
	[NgayTao] [datetime] NULL,
	[NgaySua] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KetQua]    Script Date: 2023-12-10 2:32:32 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KetQua](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Ngay] [datetime] NULL,
	[Gio] [int] NULL,
	[KetQua] [int] NULL,
	[NgayTao] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NguoiChoi]    Script Date: 2023-12-10 2:32:32 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NguoiChoi](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DienThoai] [nvarchar](10) NULL,
	[HoDem] [nvarchar](200) NULL,
	[Ten] [nvarchar](100) NULL,
	[NgaySinh] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[SP_GetDanhSachDatSo]    Script Date: 2023-12-10 2:32:32 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_GetDanhSachDatSo]
    @IDNguoiChoi INT,
	@NgayDat DATE,
	@GioDat INT
AS
BEGIN
    SELECT TOP (1000)
		ds.Id, ds.IDNguoiChoi, ds.Ngay, ds.Gio, ds.GiaTri, ds.NgayTao, ds.NgaySua, 
		HoTen = u.HoDem + ' ' + u.Ten,
		kq.KetQua, 
		IsTrung = CAST((CASE WHEN ds.GiaTri = kq.KetQua THEN 1 ELSE 0 END) AS BIT),
		NgayGioDatStr = CONVERT(VARCHAR(10), ds.Ngay, 103) + ' ' + CAST(ds.Gio AS VARCHAR(2)) + N' giờ'
	FROM dbo.DatSo ds
		INNER JOIN dbo.NguoiChoi u ON u.Id = ds.IDNguoiChoi
		LEFT JOIN dbo.KetQua kq ON kq.Ngay = ds.Ngay AND kq.Gio = ds.Gio
	WHERE 1=1
		AND (@IDNguoiChoi IS NULL OR ds.IDNguoiChoi = @IDNguoiChoi)
		AND (@NgayDat IS NULL OR ds.Ngay = @NgayDat)
		AND (@GioDat IS NULL OR ds.Gio = @GioDat)
	ORDER BY ds.Ngay DESC, ds.Gio DESC
END
GO
/****** Object:  StoredProcedure [dbo].[SP_GetDate]    Script Date: 2023-12-10 2:32:32 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--SET QUOTED_IDENTIFIER ON|OFF
--SET ANSI_NULLS ON|OFF
--GO
CREATE PROCEDURE [dbo].[SP_GetDate]
AS
BEGIN
    SELECT ThoiGian = GETDATE()
END
GO
/****** Object:  StoredProcedure [dbo].[SP_TaoKetQua]    Script Date: 2023-12-13 11:24:42 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_TaoKetQua]
    @DenNgay DATETIME,
	@NgayTao DATETIME
AS
-- Tạo kết quả @DenNgay
BEGIN
    DECLARE
		@Ngay DATETIME,
		@Gio INT,
		@TuNgay DATETIME
	DECLARE @TblIDKetQuaMoi TABLE(Id INT)

	-- lấy ngày, giờ
	IF @DenNgay IS NULL SET @DenNgay = GETDATE()
	SET @DenNgay = DATEADD(HOUR, DATEPART(HOUR, @DenNgay), CAST(CAST(@DenNgay AS DATE) AS DATETIME))

	SELECT TOP (1) @Ngay = kq.Ngay, @Gio = kq.Gio
	FROM dbo.KetQua kq 
	ORDER BY kq.Ngay DESC, kq.Gio DESC

	IF @Ngay IS NULL OR @Gio IS NULL
	BEGIN
		SELECT TOP (1) @Ngay = ds.Ngay, @Gio = ds.Gio
		FROM dbo.DatSo ds 
		ORDER BY ds.Ngay ASC, ds.Gio ASC
	END

	IF @Ngay IS NULL OR @Gio IS NULL
	BEGIN
		SET @Ngay = CAST(@DenNgay AS DATE)
		SET @Gio = DATEPART(HOUR, @DenNgay)
	END

	SET @TuNgay = DATEADD(HOUR, @Gio, CAST(CAST(@Ngay AS DATE) AS DATETIME))

	-- thêm kết quả
	BEGIN TRANSACTION
	BEGIN TRY
		;WITH RecKetQua AS (
			SELECT NgayGio = @TuNgay
			UNION ALL
			SELECT NgayGio = DATEADD(HOUR, 1, r.NgayGio)
			FROM RecKetQua r
			WHERE r.NgayGio < @DenNgay
		)

		INSERT dbo.KetQua (Ngay, Gio, KetQua, NgayTao)
		OUTPUT Inserted.Id 
		INTO @TblIDKetQuaMoi(Id)
		SELECT cr.Ngay, cr.Gio, KetQua = CAST(NULL AS INT), @NgayTao
		FROM RecKetQua r
			CROSS APPLY(SELECT 
				Ngay = CAST(r.NgayGio AS DATE),
				Gio = DATEPART(HOUR, r.NgayGio)) cR
		WHERE NOT EXISTS(SELECT 1 FROM dbo.KetQua kq 
				WHERE kq.Ngay = cR.Ngay AND kq.Gio = cR.Gio)
			AND EXISTS(SELECT 1 FROM dbo.DatSo ds
				WHERE ds.Ngay = cR.Ngay AND ds.Gio = cR.Gio)
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		DELETE @TblIDKetQuaMoi
		DECLARE @ErrorMessage NVARCHAR(4000);
		DECLARE @ErrorSeverity INT;
		DECLARE @ErrorState INT;

		SELECT 
			@ErrorMessage = ERROR_MESSAGE() + ' ' +
				'ERROR_NUMBER=' + CAST(ERROR_NUMBER() AS VARCHAR(5)) + ' ' +
				'ERROR_LINE=' + CAST(ERROR_LINE() AS VARCHAR(5)),
			@ErrorSeverity = ERROR_SEVERITY(),
			@ErrorState = ERROR_STATE();

		RAISERROR (@ErrorMessage,
				   @ErrorSeverity,
				   @ErrorState
				   );
	END CATCH
	
	-- trả về Id kết quả
	SELECT Id FROM @TblIDKetQuaMoi
END
GO