// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Server.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Server.Models
{
    public partial interface IVNVCTestContextProcedures
    {
        Task<List<SP_GetDanhSachDatSoResult>> SP_GetDanhSachDatSoAsync(int? IDNguoiChoi, DateTime? NgayDat, int? GioDat, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_TaoKetQuaResult>> SP_TaoKetQuaAsync(DateTime? DenNgay, DateTime? NgayTao, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
