// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Server.Models
{
    public partial class KetQua
    {
        public int Id { get; set; }
        public DateTime? Ngay { get; set; }
        public int? Gio { get; set; }
        public int? KetQua1 { get; set; }
        public DateTime? NgayTao { get; set; }
    }
}