// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Server.Models
{
    public partial class NguoiChoi
    {
        public int Id { get; set; }
        public string DienThoai { get; set; }
        public string HoDem { get; set; }
        public string Ten { get; set; }
        public DateTime? NgaySinh { get; set; }
    }
}