// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Server.Models
{
    public partial class SP_GetDanhSachDatSoResult
    {
        public int Id { get; set; }
        public int? IDNguoiChoi { get; set; }
        public DateTime? Ngay { get; set; }
        public int? Gio { get; set; }
        public int? GiaTri { get; set; }
        public DateTime? NgayTao { get; set; }
        public DateTime? NgaySua { get; set; }
        public string HoTen { get; set; }
        public int? KetQua { get; set; }
        public bool? IsTrung { get; set; }
        public string NgayGioDatStr { get; set; }
    }
}
