// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Server.Models
{
    public partial class SP_TaoKetQuaResult
    {
        public DateTime? Ngay { get; set; }
        public int? Gio { get; set; }
    }
}
